/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Application_HPSS */

#ifndef _Included_Application_HPSS
#define _Included_Application_HPSS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Application_HPSS
 * Method:    login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Application_HPSS_login
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     Application_HPSS
 * Method:    getFileAttr
 * Signature: (Ljava/lang/String;)LApplication/HPSSFileInfo;
 */
JNIEXPORT jobject JNICALL Java_Application_HPSS_getFileAttr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Application_HPSS
 * Method:    purgeAFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Application_HPSS_purgeAFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Application_HPSS
 * Method:    stageAFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Application_HPSS_stageAFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Application_HPSS
 * Method:    copyAFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IJ)I
 */
JNIEXPORT jint JNICALL Java_Application_HPSS_copyAFile
  (JNIEnv *, jclass, jstring, jstring, jstring, jint, jlong);

/*
 * Class:     Application_HPSS
 * Method:    writeAFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Application_HPSS_writeAFile
  (JNIEnv *, jclass, jstring, jstring, jstring, jint, jint, jstring, jstring, jint);

/*
 * Class:     Application_HPSS
 * Method:    unlinkAFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Application_HPSS_unlinkAFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Application_HPSS
 * Method:    closeSysLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Application_HPSS_closeSysLog
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
